name: CICD (Dev, Staging, Prod)

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit

  dev-deploy:
    needs: [build, unit-test]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: Development
    secrets: inherit

  staging-approval-gate:
    needs: dev-deploy
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env:
          ENV_NAME: Staging
        run: write-host "Approve for $($env.ENV_NAME)"

  staging-deploy:
    needs: staging-approval-gate
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: Staging
    secrets: inherit

  prod-approval-gate:
    needs: staging-deploy
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env:
          ENV_NAME: Production
        run: write-host "Approve for $($env.ENV_NAME)"

  prod-deploy:
    needs: prod-approval-gate
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: Production
    secrets: inherit
